language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4
  - DJANGO=1.4.3
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
before_script:
  - pyflakes -x */mirations .
script:
  - python setup.py test